image:
  # 0.8.0 images with backports come from https://github.com/abayer/tektoncd-pipeline/tree/0.8.0-for-jx
  upstreamtag: 0.8.0-jx-3
  kubeconfigwriter: gcr.io/abayer-pipeline-crd/tekton-for-jx/kubeconfigwriter
  credsinit: gcr.io/abayer-pipeline-crd/tekton-for-jx/creds-init
  gitinit: gcr.io/abayer-pipeline-crd/tekton-for-jx/git-init
  nop: gcr.io/abayer-pipeline-crd/tekton-for-jx/nop
  bash: gcr.io/abayer-pipeline-crd/tekton-for-jx/bash
  gsutil: gcr.io/abayer-pipeline-crd/tekton-for-jx/gsutil
  controller: gcr.io/abayer-pipeline-crd/tekton-for-jx/controller
  webhook: gcr.io/abayer-pipeline-crd/tekton-for-jx/webhook
  entrypoint: gcr.io/abayer-pipeline-crd/tekton-for-jx/entrypoint
  pullrequest: gcr.io/abayer-pipeline-crd/tekton-for-jx/pullrequest-init
  imagedigestexporter: gcr.io/abayer-pipeline-crd/tekton-for-jx/imagedigestexporter
  gcsfetcher: gcr.io/tekton-releases/github.com/tektoncd/pipeline/vendor/github.com/googlecloudplatform/cloud-builders/gcs-fetcher/cmd/gcs-fetcher:v0.8.0
auth:
  git:
    username:
    password:
    url: https://github.com
  docker:
    username:
    password:
    url: https://index.docker.io/v1/
    # url: https://gcr.io

controller:
  enabled: true

serviceaccount:
  enabled: true
  annotations: {}

webhook:
  enabled: true

rbac:
  cluster: true

cluster:
  resources:
    create: true
  crds:
    create: true

pvc:
  size: 5Gi
  storageClassName:
