{{- if .Values.auth.docker.configJson }}
apiVersion: v1
data:
  .dockerconfigjson: {{ .Values.auth.docker.configJson | b64enc | quote }}
kind: Secret
metadata:
  name: knative-docker-user-pass
  annotations:
    tekton.dev/docker-0: {{ .Values.auth.docker.url | quote }}
  labels:
    secret.jenkins-x.io/replica-source: "true"
type: kubernetes.io/dockerconfigjson
{{- end }}