{{- if .Values.auth.docker.username }}
apiVersion: v1
data:
  password: {{ .Values.auth.docker.password | b64enc | quote }}
  username: {{ .Values.auth.docker.username | b64enc | quote }}
  host: {{ .Values.auth.docker.host | b64enc | quote }}
kind: Secret
metadata:
  name: knative-docker-user-pass
  annotations:
    tekton.dev/docker-0: {{ .Values.auth.docker.url | quote }}
type: kubernetes.io/basic-auth
{{- end }}